FROM python:3.12-slim-bookworm

WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

COPY requirements-competitors.txt .
RUN pip install --no-cache-dir -r requirements-competitors.txt \
    && playwright install --with-deps chromium

COPY app ./app

CMD ["python", "-m", "app.competitor_main"]
