-- Companion/extra on a schedule day (not a caja shift; excluded from shift stats).
CREATE TABLE IF NOT EXISTS public.schedule_extras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drogueria_id bigint NOT NULL REFERENCES public."droguerías"(id),
  work_date date NOT NULL,
  employee_id bigint NOT NULL REFERENCES public.employees(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT schedule_extras_unique_day UNIQUE (drogueria_id, work_date)
);

CREATE INDEX IF NOT EXISTS schedule_extras_drogueria_date_idx
  ON public.schedule_extras (drogueria_id, work_date);

CREATE INDEX IF NOT EXISTS schedule_extras_employee_idx
  ON public.schedule_extras (employee_id);

DROP TRIGGER IF EXISTS schedule_extras_set_updated_at ON public.schedule_extras;
CREATE TRIGGER schedule_extras_set_updated_at
  BEFORE UPDATE ON public.schedule_extras
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.schedule_extras ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.schedule_extras IS
  'Optional companion/extra per day. Not a shift_sales slot; not joined into employee shift stats.';
