-- Ventas por turnos: config en droguerías + captura diaria.
ALTER TABLE public."droguerías"
  ADD COLUMN IF NOT EXISTS shift_count smallint NOT NULL DEFAULT 2;

ALTER TABLE public."droguerías"
  DROP CONSTRAINT IF EXISTS droguerias_shift_count_range;

ALTER TABLE public."droguerías"
  ADD CONSTRAINT droguerias_shift_count_range
  CHECK (shift_count >= 1 AND shift_count <= 6);

CREATE TABLE IF NOT EXISTS public.shift_sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drogueria_id bigint NOT NULL REFERENCES public."droguerías"(id),
  sale_date date NOT NULL,
  shift_no smallint NOT NULL,
  amount numeric(12,2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT shift_sales_shift_no_range CHECK (shift_no >= 1 AND shift_no <= 6),
  CONSTRAINT shift_sales_amount_nonneg CHECK (amount >= 0),
  CONSTRAINT shift_sales_unique_slot UNIQUE (drogueria_id, sale_date, shift_no)
);

CREATE INDEX IF NOT EXISTS shift_sales_drogueria_date_idx
  ON public.shift_sales (drogueria_id, sale_date);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS shift_sales_set_updated_at ON public.shift_sales;
CREATE TRIGGER shift_sales_set_updated_at
  BEFORE UPDATE ON public.shift_sales
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.shift_sales ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN public."droguerías".shift_count IS 'Número de turnos a capturar por día (1-6).';
COMMENT ON TABLE public.shift_sales IS 'Valor vendido por turno y día. El total del día se calcula, no se persiste.';
