-- Nequi push captures (separate from QR payments).
CREATE TABLE IF NOT EXISTS public.nequi_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client text NOT NULL,
  value numeric(12,2) NOT NULL,
  notified_at timestamptz NOT NULL,
  drogueria_id bigint NULL REFERENCES public."droguerías"(id),
  notification_key text NOT NULL,
  raw_text text NOT NULL DEFAULT '',
  device_id text NULL,
  assigned_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT nequi_payments_client_not_blank CHECK (length(trim(client)) > 0),
  CONSTRAINT nequi_payments_value_nonneg CHECK (value >= 0),
  CONSTRAINT nequi_payments_key_not_blank CHECK (length(trim(notification_key)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS nequi_payments_notification_key_uq
  ON public.nequi_payments (notification_key);

CREATE INDEX IF NOT EXISTS nequi_payments_notified_at_idx
  ON public.nequi_payments (notified_at DESC);

CREATE INDEX IF NOT EXISTS nequi_payments_drogueria_idx
  ON public.nequi_payments (drogueria_id, notified_at DESC);

CREATE INDEX IF NOT EXISTS nequi_payments_unassigned_idx
  ON public.nequi_payments (notified_at DESC)
  WHERE drogueria_id IS NULL;

DROP TRIGGER IF EXISTS nequi_payments_set_updated_at ON public.nequi_payments;
CREATE TRIGGER nequi_payments_set_updated_at
  BEFORE UPDATE ON public.nequi_payments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.nequi_payments ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.nequi_payments IS
  'Nequi push captures. drogueria_id null until assigned in frontend. Separate from QR payments.';
