-- Proveedores y facturas (uno a muchos). estado vencida se deriva al leer si sigue pendiente y ya venció.
CREATE TABLE IF NOT EXISTS public.proveedores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drogueria_id bigint NOT NULL REFERENCES public."droguerías"(id),
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT proveedores_name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS proveedores_drogueria_name_ci
  ON public.proveedores (drogueria_id, lower(name));

CREATE INDEX IF NOT EXISTS proveedores_drogueria_idx
  ON public.proveedores (drogueria_id);

CREATE TABLE IF NOT EXISTS public.facturas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drogueria_id bigint NOT NULL REFERENCES public."droguerías"(id),
  proveedor_id bigint NOT NULL REFERENCES public.proveedores(id),
  numero_factura text NOT NULL,
  fecha_factura date NOT NULL,
  fecha_vencimiento date NOT NULL,
  valor numeric(12,2) NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT facturas_numero_not_blank CHECK (length(trim(numero_factura)) > 0),
  CONSTRAINT facturas_valor_nonneg CHECK (valor >= 0),
  CONSTRAINT facturas_estado_chk CHECK (estado IN ('pendiente', 'pagada')),
  CONSTRAINT facturas_fechas_chk CHECK (fecha_vencimiento >= fecha_factura),
  CONSTRAINT facturas_unique_numero UNIQUE (drogueria_id, proveedor_id, numero_factura)
);

CREATE INDEX IF NOT EXISTS facturas_drogueria_fecha_idx
  ON public.facturas (drogueria_id, fecha_factura);

CREATE INDEX IF NOT EXISTS facturas_drogueria_estado_idx
  ON public.facturas (drogueria_id, estado);

CREATE INDEX IF NOT EXISTS facturas_proveedor_idx
  ON public.facturas (proveedor_id);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS facturas_set_updated_at ON public.facturas;
CREATE TRIGGER facturas_set_updated_at
  BEFORE UPDATE ON public.facturas
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.proveedores IS 'Proveedores por droguería. El nombre se crea al vuelo si la factura llega con string.';
COMMENT ON TABLE public.facturas IS 'estado persistido: pendiente|pagada. vencida se calcula al leer (pendiente y fecha_vencimiento <= hoy Bogotá).';
