-- Global suppliers + invoices. overdue is derived on read.
CREATE TABLE IF NOT EXISTS public.suppliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT suppliers_name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS suppliers_name_ci
  ON public.suppliers (lower(name));

CREATE TABLE IF NOT EXISTS public.invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drogueria_id bigint NOT NULL REFERENCES public."droguerías"(id),
  supplier_id bigint NOT NULL REFERENCES public.suppliers(id),
  invoice_number text NOT NULL,
  invoice_date date NOT NULL,
  due_date date NOT NULL,
  amount numeric(12,2) NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT invoices_number_not_blank CHECK (length(trim(invoice_number)) > 0),
  CONSTRAINT invoices_amount_nonneg CHECK (amount >= 0),
  CONSTRAINT invoices_status_chk CHECK (status IN ('pending', 'paid')),
  CONSTRAINT invoices_dates_chk CHECK (due_date >= invoice_date),
  CONSTRAINT invoices_unique_number UNIQUE (supplier_id, invoice_number)
);

CREATE INDEX IF NOT EXISTS invoices_drogueria_date_idx
  ON public.invoices (drogueria_id, invoice_date);

CREATE INDEX IF NOT EXISTS invoices_drogueria_status_idx
  ON public.invoices (drogueria_id, status);

CREATE INDEX IF NOT EXISTS invoices_supplier_idx
  ON public.invoices (supplier_id);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS invoices_set_updated_at ON public.invoices;
CREATE TRIGGER invoices_set_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.suppliers IS 'Global supplier catalog shared by all droguerias.';
COMMENT ON TABLE public.invoices IS 'Stored status is pending|paid. overdue is derived on read when pending and due_date <= today America/Bogota.';
