-- Global employees + per-slot schedule. Stats join to shift_sales.
CREATE TABLE IF NOT EXISTS public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT employees_name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS employees_name_ci
  ON public.employees (lower(name));

CREATE TABLE IF NOT EXISTS public.shift_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drogueria_id bigint NOT NULL REFERENCES public."droguerías"(id),
  work_date date NOT NULL,
  shift_no smallint NOT NULL,
  employee_id bigint NOT NULL REFERENCES public.employees(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT shift_assignments_shift_no_range CHECK (shift_no >= 1 AND shift_no <= 6),
  CONSTRAINT shift_assignments_unique_slot UNIQUE (drogueria_id, work_date, shift_no)
);

CREATE INDEX IF NOT EXISTS shift_assignments_drogueria_date_idx
  ON public.shift_assignments (drogueria_id, work_date);

CREATE INDEX IF NOT EXISTS shift_assignments_employee_idx
  ON public.shift_assignments (employee_id);

DROP TRIGGER IF EXISTS shift_assignments_set_updated_at ON public.shift_assignments;
CREATE TRIGGER shift_assignments_set_updated_at
  BEFORE UPDATE ON public.shift_assignments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_assignments ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.employees IS 'Shared employee catalog for all droguerias.';
COMMENT ON TABLE public.shift_assignments IS 'One row per schedule cell. Missing row = empty cell.';
